const SITE = 'https://kuriamyg.github.io/coderiserdigital';

export const pages = [
  {
    id: 'home',
    file: 'index.html',
    source: 'home.html',
    navLabel: 'Home',
    title: 'Moses Mwangi Kuria — Software Engineer',
    description: 'Software engineer in Nairobi, Kenya, building fintech systems, security-first engineering practices, and practical tools. See PesaFlow, TrustGiving, and other work.',
    ogTitle: 'Moses Mwangi Kuria — Software Engineer',
    ogDescription: 'Full-stack engineering where money, trust, or risk are involved. A live Kenya-first budgeting app, a church finance system with audit-grade integrity, and more.',
    canonical: SITE,
  },
  {
    id: 'projects',
    file: 'projects.html',
    source: 'projects.html',
    navLabel: 'Projects',
    title: 'Projects — Moses Mwangi Kuria',
    description: 'PesaFlow (a live Kenya-first budgeting app), TrustGiving (a church finance system with audit-grade integrity), a trading expectancy journal, and other work.',
    ogTitle: 'Projects — Moses Mwangi Kuria',
    ogDescription: 'A live fintech app, a financial system of record, and other things I have built.',
    canonical: `${SITE}/projects.html`,
  },
  {
    id: 'about',
    file: 'about.html',
    source: 'about.html',
    navLabel: 'About',
    title: 'About — Moses Mwangi Kuria',
    description: 'How I build software: understand the real problem first, treat correctness as non-negotiable where money is involved, and ship working versions over big-bang rewrites.',
    ogTitle: 'About — Moses Mwangi Kuria',
    ogDescription: 'Software engineer based in Nairobi, Kenya. How I think about building financial and security-critical systems.',
    canonical: `${SITE}/about.html`,
  },
  {
    id: 'skills',
    file: 'skills.html',
    source: 'skills.html',
    navLabel: 'Skills',
    title: 'Skills — Moses Mwangi Kuria',
    description: 'Next.js, React, TypeScript, NestJS, Prisma, PostgreSQL, security engineering, AI integration, and more.',
    ogTitle: 'Skills — Moses Mwangi Kuria',
    ogDescription: 'The stack and practices behind the projects — frontend, backend, databases, security, and AI integration.',
    canonical: `${SITE}/skills.html`,
  },
  {
    id: 'contact',
    file: 'contact.html',
    source: 'contact.html',
    navLabel: 'Contact',
    title: 'Contact — Moses Mwangi Kuria',
    description: 'Open to freelance projects, collaboration, and interesting engineering problems. Get in touch on WhatsApp, email, or GitHub.',
    ogTitle: 'Contact — Moses Mwangi Kuria',
    ogDescription: "Let's talk — WhatsApp, email, or GitHub.",
    canonical: `${SITE}/contact.html`,
  },
];
