const SITE = 'https://kuriamyg.github.io/coderiserdigital';

export const pages = [
  {
    id: 'home',
    file: 'index.html',
    source: 'home.html',
    navLabel: 'Home',
    title: 'CodeRise Digital — Professional Web Development in Nairobi',
    description: 'Professional web development studio in Nairobi. Custom websites built from scratch — no templates, no shortcuts. Packages from KSh 8,000. First 5 clients get a FREE domain.',
    ogTitle: 'CodeRise Digital — No Templates. No Shortcuts.',
    ogDescription: 'We build professional websites for real businesses. Packages from KSh 8,000 — landing pages to full e-commerce. First 5 clients get a free domain!',
    canonical: SITE,
  },
  {
    id: 'packages',
    file: 'packages.html',
    source: 'packages.html',
    navLabel: 'Packages',
    title: 'Packages & Pricing — CodeRise Digital',
    description: 'Transparent website packages from KSh 8,000 — Starter, Business Pro, and Premium. Hosting included from day one. No hidden costs.',
    ogTitle: 'CodeRise Digital — Packages & Pricing',
    ogDescription: 'Starter from KSh 8,000, Business Pro KSh 22,000, Premium KSh 50,000 — transparent pricing, hosting included, no hidden costs.',
    canonical: `${SITE}/packages.html`,
  },
  {
    id: 'process',
    file: 'process.html',
    source: 'process.html',
    navLabel: 'Process',
    title: 'Our Process & Security — CodeRise Digital',
    description: 'How we build your website: brief, build, launch — plus the security practices every CodeRise Digital project gets by default.',
    ogTitle: 'CodeRise Digital — Our Process & Security',
    ogDescription: 'See exactly how we build your site, and the security standards every project gets by default.',
    canonical: `${SITE}/process.html`,
  },
  {
    id: 'ai',
    file: 'ai.html',
    source: 'ai.html',
    navLabel: 'AI Add-ons',
    title: 'AI Add-ons — CodeRise Digital',
    description: 'Add a live AI chatbot, lead qualifier, booking assistant, or smart search to your website. Available on Business Pro and Premium packages.',
    ogTitle: 'CodeRise Digital — AI-Powered Website Add-ons',
    ogDescription: 'Live AI chatbots, booking assistants, smart search and more — integrated directly into your website.',
    canonical: `${SITE}/ai.html`,
  },
  {
    id: 'faq',
    file: 'faq.html',
    source: 'faq.html',
    navLabel: 'FAQ',
    title: 'FAQ & Contact — CodeRise Digital',
    description: 'Answers to common questions about pricing, ownership, timelines and support — plus how to start your project on WhatsApp.',
    ogTitle: 'CodeRise Digital — FAQ & Contact',
    ogDescription: 'Everything you need to know before starting your project, and how to reach us on WhatsApp.',
    canonical: `${SITE}/faq.html`,
  },
];
